spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password:

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/xu
    type: com.alibaba.druid.pool.DruidDataSource

# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: "接口文档信息"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com